version: '3.8'
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://s224806968_postgresql_ubus_user:PBGp4wBfZMslGy5oyACtETlbXm0SNZYs@dpg-crertn2j1k6c73dfr76g-a.singapore-postgres.render.com/s224806968_postgresql_ubus
    restart: "no"

  inventory_management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://s224806968_postgresql_ubus_user:PBGp4wBfZMslGy5oyACtETlbXm0SNZYs@dpg-crertn2j1k6c73dfr76g-a.singapore-postgres.render.com/s224806968_postgresql_ubus
    restart: "no"
